### ISSUE TITLE
Use latest LTS 12.13.1 "Erbium"

### ISSUE THREAD

**Issue by jdtron** [ion2s-gmbh/vbox#9]
Includes npm version 6.12.1.

This would be a quick win, changing provisioning to this version.
`nvm install --lts=Erbium --latest-npm`

@sebbaum what do you think?
Maybe I could update that soon.

**Comment by sebbaum** [comment]
@jdtron Good idea, go for it. :+1: 
Send a PR and I will merge it.

Cheers Sebastian
